### ISSUE TITLE
Match the export sent to Scripps to geocodes and media markets

### ISSUE THREAD

**Issue by dheerajchand** [CircaVictor/geocoding#5]
We'll need to append media markets and long/lats to the export sent to Scripps.

**Comment by dheerajchand** [comment]
You'll need to ensure that the address hashes in the `locations` table and the `donations` table are made in the same way so that we can use them for matching.

**Comment by dheerajchand** [comment]
In Jefferson, there are two tables that are usable for the match: 

1. `scripps_forms_sample_export`
2. `scripps_expenditures_sample_report`

You will need to match both, I think. The SQL to create them can be found [here](https://github.com/CircaVictor/Jefferson/wiki/SQL-Data-Requests-Sales-Samples-Scripps). 

LMK if there are questions.

**Comment by jpkramer** [comment]
[scripps_presidential_expenditures_sample_export_last_30_days_with_locations.sql.zip](https://github.com/CircaVictor/geocoding/files/350851/scripps_presidential_expenditures_sample_export_last_30_days_with_locations.sql.zip)

**Comment by justinhernandez** [comment]
What's happening with @dheerajchand why is this export not forwarded to sales? Are you planning on doing that? What is the next steps so this export can be useful.

Please communicate here.

@jpkramer said he informed you that I asked him to email this zip to me. Is this a new flow. Do we have to monitor all issues if we are not flagged? How do we get this to sales and how does this issue process alleviate the reason this data exists in the first place:

Getting this data set into the hands of the customer?

**Comment by justinhernandez** [comment]
I'll send this along to @tylercv.

Closing the issue and not flagging or communicating next steps is not the solution.

**Comment by dheerajchand** [comment]
I'll answer your questions in order:

1. This file was not sent directly to Sales because I wanted to have it easily archived in a location, reachable by all of us, rather than living _only_ in an email attachment.  

2. I had planned on sending to Tyler myself with explanatory language to send to Scripps, and just conferred with him to inform him that both were en route.

3. I misunderstood @jpkramer, it seems. I thought he said that you had instructed him to use pg_dump, not to email sales and the client directly.  

I am sorry that my actions caused you stress, rather than relieving it. That language for sales is being written right now.

**Comment by justinhernandez** [comment]
@dheerajchand Ok I misunderstood the arrangement. I thought I was the point of contact. Did not realize you were going to take over that process. That is fine.

Please make sure to include the `scripps_presidential_forms_sample_export_last_30_days.sql` sql file in the zip that is sent along to Scripps. Thanks @jpkramer @dheerajchand 👍

**Comment by justinhernandez** [comment]
Adding the zipped `forms` export here just in case cc: @dheerajchand 

[scripps_presidential_forms_sample_export_last_30_days.sql.zip](https://github.com/CircaVictor/geocoding/files/350901/scripps_presidential_forms_sample_export_last_30_days.sql.zip)
